# Generated by Django 2.2.1 on 2020-03-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200328_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='down_vote',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='up_vote',
        ),
    ]
