# Generated by Django 2.2.1 on 2020-04-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200328_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('L', 'Love'), ('A', 'Angry'), ('U', 'Up Vote'), ('D', 'Down Vote')], max_length=1),
        ),
    ]
